#ifndef CONSTANTS_H
#define CONSTANTS_H

#ifndef DECLARE_CONSTANT
#error "File constants.h cannot be included directly"
#endif

#include "value.h"

DECLARE_CONSTANT(RTtoF);
DECLARE_CONSTANT(FtoRT);
DECLARE_CONSTANT(Decrease);
DECLARE_CONSTANT(K_OUT);
DECLARE_CONSTANT(G_KR);
DECLARE_CONSTANT(d_NCX);
DECLARE_CONSTANT(k_NCX);
DECLARE_CONSTANT(SIGMA);
DECLARE_CONSTANT(ENa);
DECLARE_CONSTANT(EK);
DECLARE_CONSTANT(EKs);
DECLARE_CONSTANT(ACAP);
DECLARE_CONSTANT(V_MYO);
DECLARE_CONSTANT(V_NSR);
DECLARE_CONSTANT(V_JSR);
DECLARE_CONSTANT(pump_factor);
DECLARE_CONSTANT(Spacestep_2);
DECLARE_CONSTANT(Diff_to_Step_2);
DECLARE_CONSTANT(Diff_to_Step_8);

#endif	/* CONSTANTS_H */
